// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1B7hYSTJ521w29ypNswYymt6AtftCGRY',
    appId: '1:1095445790766:web:261ffcad3f2e1b69481fbf',
    messagingSenderId: '1095445790766',
    projectId: 'aoj-344475',
    authDomain: 'aoj-344475.firebaseapp.com',
    storageBucket: 'aoj-344475.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDDS1Ltr61aAVnZAoo7EIT6wsFSSs9ICs',
    appId: '1:1095445790766:android:71ecedbb9f5b1125481fbf',
    messagingSenderId: '1095445790766',
    projectId: 'aoj-344475',
    storageBucket: 'aoj-344475.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHJVZFHIsPvtG15MBGZLzRtelXKfKPD3I',
    appId: '1:1095445790766:ios:160742db0f33d80d481fbf',
    messagingSenderId: '1095445790766',
    projectId: 'aoj-344475',
    storageBucket: 'aoj-344475.appspot.com',
    iosClientId: '1095445790766-m42rtbbf256sc3olhjcul2sq26qqpur6.apps.googleusercontent.com',
    iosBundleId: 'com.example.allPersistenceTypes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHJVZFHIsPvtG15MBGZLzRtelXKfKPD3I',
    appId: '1:1095445790766:ios:160742db0f33d80d481fbf',
    messagingSenderId: '1095445790766',
    projectId: 'aoj-344475',
    storageBucket: 'aoj-344475.appspot.com',
    iosClientId: '1095445790766-m42rtbbf256sc3olhjcul2sq26qqpur6.apps.googleusercontent.com',
    iosBundleId: 'com.example.allPersistenceTypes',
  );
}
